### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by blue0125** [i5ting/How-to-learn-node-correctly#13]
1.npm（node packages manager）【内置，替代品是n或nvs（对win也支持）】
这里 n 是TJ 的 [N](https://github.com/TJ/N) 吗？那应该是 nvm 非 win 的替代品吧。

2.npm install xxx | 安装xxx模块，但不记录到package.json里
[npm install](https://docs.npmjs.com/cli/install) 文档里是 
By default, npm install will install all modules listed as dependencies in package.json.
npm install saves any specified packages into dependencies by default. 

文档里也找不到 -s 参数。记得以前是有的。
是不是因为新版本npm 有改动。 会不会记录到 package.json，和命令参数没关系，只有根目录里有 package.json 文件 npm i 安装的包才会写入package.json。

**Comment by i5ting** [comment]
1）nvm和n是一样的，非win。nvs全支持 2）-s是--save，不加不会保存的

**Comment by blue0125** [comment]
@i5ting 我表达有误哈。

1. 其实想表达的是 npm 包管理工具，和 n node 版本管理工具两者维度不一样不能比较吧。n nvm 才都是node版本版本控制器。

2.  安装包的时候 -S -D 是说明包的环境依赖，和记录不记录到package.json 没关系。
又去重新查看了下npm 文档，没有找到-S，但还是可以用。
-P, --save-prod: Package will appear in your dependencies. This is the default unless -D or -O are present.
-D, --save-dev: Package will appear in your devDependencies.

**Comment by pujiaxun** [comment]
@blue0125  之前的版本里 -S 和 -D 与记录不记录到 package.json  **确实有关系**。

之前的版本里，不加额外的参数，是不会保存到package.json，加了-S会保存到dependencies，加-D会保存到devDependencies。

**最新版的 npm 是默认保存的**，即默认-S的效果，需要 --no-save 来避免更新到package.json。所以你在文档里找不到-S了…

**Comment by blue0125** [comment]
@pujiaxun 是的。npm 更新了版本，所以这边是比较老的知识了哈。

**Comment by pujiaxun** [comment]
哈，这就是我提的 = =。。
提完看到了这个issue

blue0125 <notifications@github.com> 于2019年1月7日周一 下午6:52写道：
