### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by 77Vincent** [i5ting/How-to-learn-node-correctly#3]
“Node核心：异步流程控制”章节中：

DIRT（数据敏感实时应用）翻译有误

Data Intensive Real Time，应为“数据密集实时应用”

**Comment by i5ting** [comment]
感谢，确实是敲错了，方便来个pr么？

**Comment by chinesedfan** [comment]
@i5ting #9 随手改了，:)

**Comment by i5ting** [comment]
感谢，已合并
